### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by KudouUsagi** [iczman/userscripts#1]
They updated the page and this no longer works. Would you be able to update it?

**Comment by iczman** [comment]
Thank you for reporting, but I couldn't reproduce your issue.

Could you elaborate what happened and what you saw? Did it work for you before?

**Comment by KudouUsagi** [comment]
Sorry I figured it out! I was trying to use Greasemonkey but it's set up for tampermonkey. I was setting it up on a new computer and didn't realize I had used tampermonkey before.

**Comment by iczman** [comment]
I’m glad you were able to figure it out :)
